FROM python:3.9.4-slim
WORKDIR /tests/python
RUN pip install pipenv
COPY python/Pipfile python/Pipfile.lock /tests/python/
RUN pipenv install
CMD ["./wait-for-sc.sh", "pipenv", "run", "tests"]
COPY python/conftest.py python/tests.py wait-for-sc.sh /tests/python/
RUN chmod +x wait-for-sc.sh
